### PR TITLE
Implement support for multiple recipients, CCs and BCCs

### PR DESCRIPTION
**Pull request by coreymcmahon**
Few different fixes/improvements here:

* Integrates `laravel/pint` for code formatting and fixes the coding standards
* Fixes a bug with `mergeConfigFrom()` using `bento` instead of `bentonow`
* Throws `TransportException` instead of swallowing exceptions. It's better to let the exception bubble up so it doesn't fail silently (also allows us to retry if the mail is sent in a background job)
* Adds support for multiple recipients and carbon copies
* Adds support for BCCs, which aren't supported by the API _yet_ but should be soon (based on Jesse's feedback).

I also renamed the config keys to use `snake_case` instead of `camelCase` to make it consistent with other Laravel conventions. There's a fallback to the `camelCase` version so it won't break existing installs.

### CODE REVIEW

**Comment by coreymcmahon** [comment]
Hi @jessehanley, pushed some improvements/fixes here. Should all be backwards compatible and tests are green, but please let me know if you have any questions/concerns or would like something handled differently 🙏

**Comment by jessehanley** [comment]
@coreymcmahon merged! Believe @ziptied is working on some stuff atm, when I merge his stuff in I'll cut a release. Appreciate you @coreymcmahon. I've credited your account $100 for the work!

**Comment by ziptied** [comment]
@coreymcmahon legend, thanks for the contributions

**Comment by coreymcmahon** [comment]
Awesome! Thanks for the quick merge (and free credits). Really appreciated 🙏

**Pull request merged**
